

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Starter pipeline
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ME-MngEnvMCAP860456-lalitava-1(e6822116-bf10-4884-984e-84e4ab526d4e)'
    appType: 'webApp'
    WebAppName: 'talapoappserv'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
